### PR TITLE
Correct OSCAL version handling in resolved profile

### LINKED ISSUE #15: Profile resolution incorrectly maps the `oscal-version` from the `version` on the source profile
# Describe the bug

Profile resolution incorrectly maps the `oscal-version` from the `version` on the source profile. 

# Who is the bug affecting?
Users using the profile resolution functionality.

# What is affected by this bug?

Provides incorrect profile resolution output.
Resolving the following:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="../example-checkup.sch" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<!-- Modified by conversion XSLT 2021-04-05T11:22:07.701-04:00 - RC2 OSCAL becomes RC3 OSCAL -->
<profile xmlns="http://csrc.nist.gov/ns/oscal/1.0"
         uuid="cb1ec926-3441-458f-8cce-ea11308c9d37">
   <metadata>
      <title>Test Profile</title>
      <last-modified>2020-05-30T14:39:35.84-04:00</last-modified>
      <version>2.3.4</version>
      <oscal-version>1.0.3</oscal-version>
   </metadata>
   <import href="catalogs/abc-simple_catalog.xml">
      <include-controls with-child-controls="yes">
         <with-id>a1</with-id>
         <with-id>b1</with-id>
         <with-id>c1</with-id>
         <with-id>c3</with-id>
      </include-controls>
   </import>
</profile>
```
Will result in:
```xml
<?xml version='1.0' encoding='UTF-8'?>
<catalog xmlns="http://csrc.nist.gov/ns/oscal/1.0" uuid="bd50d038-64e2-49ef-9524-c8172d77cbaf">
  <metadata>
    <title>Test Profile</title>
    <last-modified>2022-05-10T10:47:25.3088315Z</last-modified>
    <version>2.3.4</version>
    <oscal-version>2.3.4</oscal-version>
    <prop name="resolution-tool" value="libOSCAL-Java"/>
    <link href="file:/******/liboscal-java/oscal/src/specifications/profile-resolution/profile-resolution-examples/base-test_profile.xml" rel="source-profile"/>
  </metadata>
  <control id="a1">
    <title>Control A1</title>
    <prop name="label" value="first"/>
    <part id="a1-stmt" name="statement">
      <p>A1 aaaaa aaaaaaaaaa</p>
    </part>
  </control>
  <control id="b1">
    <title>Control B1</title>
    <prop name="label" value="fourth"/>
    <part id="b1-stmt" name="statement">
      <p>B1 bbbb bbbbbbb.</p>
    </part>
  </control>
  <control id="c1">
    <title>Control C1</title>
    <prop name="label" value="seventh"/>
    <part id="c1-stmt" name="statement">
      <p>C1 ccccc ccc ccccccccccccccccc.</p>
    </part>
  </control>
  <control id="c3">
    <title>Control C3</title>
    <prop name="label" value="ninth"/>
    <part id="c3-stmt" name="statement">
      <p>C3 ccccc cccccccccccccc.</p>
    </part>
  </control>
  <control id="c3.a">
    <title>Control C3-A</title>
    <prop name="label" value="tenth"/>
    <part id="c3-stmt" name="statement">
      <p>C3 A ccccc cccccccccccccc.</p>
    </part>
  </control>
  <control id="c3.a-1">
    <title>Control C3-A-1</title>
    <prop name="label" value="eleventh"/>
    <part id="c3-stmt" name="statement">
      <p>C3 A-1 ccccc cccccccccccccc.</p>
    </part>
  </control>
</catalog>
```

# When does this occur?

On profile resolution.

# How do we replicate the issue?

Add the below (Illustrative only) test to [`ProfileResolutionTests`](https://github.com/usnistgov/liboscal-java/blob/main/src/test/java/gov/nist/secauto/oscal/lib/profile/resolver/ProfileResolutionTests.java).

```java
@Test  
void testOscalVersion() throws IllegalStateException, IOException, BindingException, SaxonApiException {  
  String injectedOscalVersion = "1.0.3";  
  String profileLocation = String.format("%s/%s_profile.xml", PROFILE_PATH, "base-test");  
  File profileFile = new File(profileLocation);  
  Profile profile = OscalBindingContext.instance().loadProfile(profileFile);  
  profile.getMetadata().setOscalVersion(injectedOscalVersion);  
  ProfileResolver.ResolutionData data  
          = new ProfileResolver.ResolutionData(profile, ObjectUtils.notNull(profileFile.toURI()), new Stack<>());  
  getProfileResolver().resolve(data);  
  Catalog actual = data.getCatalog();  
  Assertions.assertThat(actual.getMetadata().getOscalVersion()).isEqualTo(injectedOscalVersion);  
}
```

# Expected behavior (i.e. solution)

See `Assertions` above.

# Other Comments

None

### PR DESCRIPTION
**Pull request by david-waltermire-nist**
# Committer Notes

Corrected metadata/oscal-version handling bug to use OSCAL version, not the content version from a source profile. Resolves #15.

### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/usnistgov/oss-maven/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/oss-maven/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Do all automated CI/CD checks pass?

### Changes to Core Features:

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your core changes, as applicable?
- [ ] Have you included examples of how to use your new feature(s)?
- [ ] Have you updated all website and readme documentation affected by the changes you made?

### CODE REVIEW

File: src/main/java/gov/nist/secauto/oscal/lib/profile/resolver/ProfileResolver.java [hunk 1]
```diff
@@ -134,8 +134,14 @@ public void resolve(@NotNull ResolutionData data) throws IOException, IllegalSta
...
     metadata.setTitle(profile.getMetadata().getTitle());
-    metadata.setVersion(profile.getMetadata().getVersion());
-    metadata.setOscalVersion(OscalUtils.OSCAL_VERSION);
+
+    if (profile.getMetadata().getVersion() != null) {
+      metadata.setVersion(profile.getMetadata().getVersion());
+    }
+
+//    metadata.setOscalVersion(OscalUtils.OSCAL_VERSION);
+    metadata.setOscalVersion(data.getProfile().getMetadata().getOscalVersion());
```
Comment (aj-stein-nist) [inline src/main/java/gov/nist/secauto/oscal/lib/profile/resolver/ProfileResolver.java:143]: OK, you will love this feedback in the PR. I decided to read the [profile resolution spec](https://github.com/usnistgov/OSCAL/blob/adc51808988404448fddc9b85da7c5084e6a03af/src/specifications/profile-resolution/profile-resolution-specml.xml#L1391-L1393) to make sure I understood this bit a few times.

> The value of metadata:oscal-version in the target MUST be set with a string that identifies the version of OSCAL used by this tool to resolve the profile (ex. 1.0.0). This value MUST be determined by compiling the oscal-versions from each imported document and the source profile, and taking the most recent minor version. If this version is more recent than what the resolution tool is using, then the value of oscal-version MUST be the version that the tool used internally. If any of the above OSCAL versions (imported document versions, source profile version, tool version) are of a different major version (the first digit differs), the tool SHOULD provide an error and cease processing.

What you have done is definitely good, but we specify _minor_ version, not _patch_ version `currently in this PR the constant is set to `1.0.4.`.

Is this a specification issue or a code issue?

Comment (david-waltermire-nist) [reply src/main/java/gov/nist/secauto/oscal/lib/profile/resolver/ProfileResolver.java:143]: I believe this is a spec issue. Would you open an issue on the spec?

Comment (aj-stein-nist) [reply src/main/java/gov/nist/secauto/oscal/lib/profile/resolver/ProfileResolver.java:143]: https://github.com/usnistgov/OSCAL/issues/1272

**Review by aj-stein-nist — APPROVED** [review]
